#!/usr/bin/env python3
"""Build and install a Skill package from a validated internal Method Contract.

The source-sufficiency hook intentionally stops at an internal contract.  This
module is the next, deterministic layer: it accepts only that contract shape,
renders a small package, and provides idempotent create/update/install
operations.  It does not import or copy ``writing-great-skills`` at runtime.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import re
import shutil
import sys
import tempfile
from pathlib import Path
from typing import Any, Iterable


REQUIRED_CONTRACT_FIELDS = (
    "purpose",
    "triggers",
    "invocation_type",
    "inputs",
    "ordered_method",
    "decisions",
    "constraints",
    "failure_modes",
    "outputs",
    "resources",
    "verification",
    "unresolved_gaps",
    "confidence",
)

ALLOWED_INVOCATIONS = frozenset({"user-invoked", "model-invoked"})
PLACEHOLDER_RE = re.compile(
    r"(?:^|[^a-z0-9])(?:tbd|todo|unknown|placeholder|n/?a|not applicable|"
    r"not available|to be determined|"
    r"to be completed|coming soon)(?:$|[^a-z0-9])",
    re.IGNORECASE,
)
GENERIC_BOILERPLATE_RE = re.compile(
    r"^(?:add|describe|document|insert|provide)\s+(?:the\s+)?"
    r"(?:purpose|triggers?|inputs?|ordered method|workflow|steps?|"
    r"decisions?|decision rules|constraints?|failure modes?|outputs?|"
    r"verification|details)(?:\s+here)?$|"
    r"^use when an ai agent needs to repeat the .+ method from source notes, "
    r"transcripts, project files, or user corrections$|"
    r"^return the generated or updated skill files plus a concise verification summary$",
    re.IGNORECASE,
)
STANDALONE_PLACEHOLDERS = frozenset(
    {
        "",
        "-",
        "...",
        "…",
        "[]",
        "[ ]",
        "<placeholder>",
        "[placeholder]",
        "placeholder",
        "tbd",
        "todo",
        "n/a",
        "na",
        "n.a.",
        "unknown",
        "not applicable",
        "not available",
        "not applicable",
        "to be determined",
        "to be completed",
        "coming soon",
    }
)
EXPLICIT_NO_RESOURCE_MARKERS = frozenset(
    {
        "none",
        "no resource",
        "no resources",
        "no resource needed",
        "no resources needed",
        "no resource required",
        "no resources required",
    }
)
GUARDRAIL_RE = re.compile(
    r"\b(?:do not|don't|never|avoid|must not|must never|fails? if|blocks? if|"
    r"is blocked when|stop (?:if|when)|rejects? if|errors? if|raises? if|"
    r"refuses? if|returns? .*? if)\b|不要|禁止|不得|避免",
    re.IGNORECASE,
)
NAME_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
MARKER_RE = re.compile(r"^<!-- Generated by learn-anything package build\. Contract revision: ([0-9a-f]{64}) -->$")
WINDOWS_ABSOLUTE_RE = re.compile(r"^[A-Za-z]:[\\/]|^\\\\")
MANAGED_MANIFEST = ".learn-anything-managed.json"


class PackageBuildError(ValueError):
    """Raised when a contract or package boundary cannot be trusted."""


def _standalone_placeholder(value: str) -> bool:
    normalized = re.sub(r"\s+", " ", value).strip().strip("` ").rstrip(".!?:;,").strip().lower()
    if normalized in STANDALONE_PLACEHOLDERS:
        return True
    return normalized.strip("[]<>{}() ") in STANDALONE_PLACEHOLDERS


def _unresolved_value(value: str, *, allow_guardrail: bool = False) -> bool:
    if _standalone_placeholder(value):
        return True
    if not allow_guardrail and GENERIC_BOILERPLATE_RE.fullmatch(value.strip()):
        return True
    if not PLACEHOLDER_RE.search(value):
        return False
    return not (allow_guardrail and GUARDRAIL_RE.search(value))


def _as_nonempty_strings(
    value: Any,
    field: str,
    *,
    minimum: int = 1,
    reject_placeholders: bool = True,
) -> list[str]:
    if not isinstance(value, list):
        raise PackageBuildError(f"{field} must be a list of strings")
    values = [item.strip() for item in value if isinstance(item, str) and item.strip()]
    if len(values) < minimum or len(values) != len(value):
        raise PackageBuildError(f"{field} contains missing or non-string values")
    if reject_placeholders and any(_unresolved_value(item, allow_guardrail=field in {"constraints", "failure_modes"}) for item in values):
        raise PackageBuildError(f"{field} contains unresolved placeholder evidence")
    return values


def _contract_from_payload(payload: dict[str, Any]) -> dict[str, Any]:
    """Extract an internal contract while rejecting non-promotable results."""

    if not isinstance(payload, dict):
        raise PackageBuildError("contract payload must be a JSON object")

    if "method_contract" in payload:
        if payload.get("outcome") != "method_contract":
            raise PackageBuildError("package build requires outcome=method_contract")
        if payload.get("promotion_status") != "eligible_for_package_build":
            raise PackageBuildError("package build requires an eligible promotion status")
        if payload.get("contract_visibility") != "internal":
            raise PackageBuildError("the Method Contract must remain internal")
        if payload.get("source_kind") != "reusable_method":
            raise PackageBuildError("package build requires a reusable_method source kind")
        contract = payload["method_contract"]
    else:
        contract = payload

    if not isinstance(contract, dict):
        raise PackageBuildError("method_contract must be a JSON object")
    return contract


def validate_contract(payload: dict[str, Any]) -> dict[str, Any]:
    """Validate and return a normalized contract ready for rendering."""

    contract = _contract_from_payload(payload)
    missing = [field for field in REQUIRED_CONTRACT_FIELDS if field not in contract]
    if missing:
        raise PackageBuildError(f"missing contract fields: {', '.join(missing)}")

    purpose = contract["purpose"]
    if not isinstance(purpose, str) or not purpose.strip() or _unresolved_value(purpose):
        raise PackageBuildError("purpose must be concrete source evidence")
    invocation_type = contract["invocation_type"]
    if not isinstance(invocation_type, str) or invocation_type not in ALLOWED_INVOCATIONS:
        raise PackageBuildError("invocation_type must be user-invoked or model-invoked")
    unresolved_gaps = contract["unresolved_gaps"]
    if not isinstance(unresolved_gaps, list) or unresolved_gaps != []:
        raise PackageBuildError("unresolved_gaps must be empty before package build")
    confidence = contract["confidence"]
    if (
        isinstance(confidence, bool)
        or not isinstance(confidence, (int, float))
        or not math.isfinite(float(confidence))
        or not 0 <= confidence <= 1
    ):
        raise PackageBuildError("confidence must be a number between 0 and 1")

    for field in ("title", "name"):
        value = contract.get(field)
        if value is not None and (
            not isinstance(value, str) or not value.strip() or _unresolved_value(value)
        ):
            raise PackageBuildError(f"{field} must be concrete source evidence")

    normalized: dict[str, Any] = dict(contract)
    normalized["purpose"] = purpose.strip()
    normalized["triggers"] = _as_nonempty_strings(contract["triggers"], "triggers")
    normalized["inputs"] = _as_nonempty_strings(contract["inputs"], "inputs")
    normalized["ordered_method"] = _as_nonempty_strings(contract["ordered_method"], "ordered_method", minimum=2)
    normalized["decisions"] = _as_nonempty_strings(contract["decisions"], "decisions")
    # A guardrail may legitimately say “do not leave TBD markers”; it is not
    # itself unresolved evidence. The source gate applies the same distinction.
    normalized["constraints"] = _as_nonempty_strings(contract["constraints"], "constraints")
    normalized["failure_modes"] = _as_nonempty_strings(contract["failure_modes"], "failure_modes")
    normalized["outputs"] = _as_nonempty_strings(contract["outputs"], "outputs")
    normalized["verification"] = _as_nonempty_strings(contract["verification"], "verification")

    resources = _as_nonempty_strings(contract["resources"], "resources", reject_placeholders=False)
    resource_markers = {
        re.sub(r"\s+", " ", value).strip().rstrip(".!?:;,").lower() for value in resources
    }
    if len(resources) == 1 and resource_markers <= EXPLICIT_NO_RESOURCE_MARKERS:
        normalized["resources"] = ["none"]
    else:
        if resource_markers & EXPLICIT_NO_RESOURCE_MARKERS:
            raise PackageBuildError("resources cannot mix an explicit no-resource marker with resources")
        if any(_unresolved_value(value) for value in resources):
            raise PackageBuildError("resources contains unresolved placeholder evidence")
        resource_paths = [_resource_path(value) for value in resources]
        if any(not path for path in resource_paths):
            raise PackageBuildError("resources contains an empty resource path")
        if len(set(resource_paths)) != len(resource_paths):
            raise PackageBuildError("resources contains duplicate declarations")
        normalized["resources"] = resources

    evidence = contract.get("source_evidence", {})
    if evidence is not None and not isinstance(evidence, dict):
        raise PackageBuildError("source_evidence must be an object when present")
    normalized_evidence: dict[str, list[str]] = {}
    for label, values in (evidence or {}).items():
        if not isinstance(label, str) or not label.strip() or not isinstance(values, list):
            raise PackageBuildError("source_evidence values must be lists of strings")
        if any(not isinstance(value, str) or not value.strip() for value in values):
            raise PackageBuildError("source_evidence contains missing or non-string values")
        normalized_evidence[label.strip()] = [value.strip() for value in values]
    normalized["source_evidence"] = normalized_evidence
    return normalized


def slugify(value: str) -> str:
    """Return a safe kebab-case Skill name derived from a contract title."""

    value = re.sub(r"[^a-zA-Z0-9]+", "-", value).strip("-").lower()
    value = re.sub(r"-+", "-", value)
    if not value:
        raise PackageBuildError("skill name cannot be derived from an empty title")
    if len(value) > 63:
        value = value[:63].rstrip("-")
    if not NAME_RE.fullmatch(value):
        raise PackageBuildError("skill name must be kebab-case")
    return value


def _name_for_contract(contract: dict[str, Any], requested: str | None) -> str:
    candidate = requested or contract.get("name") or contract.get("title")
    if not isinstance(candidate, str) or not candidate.strip():
        raise PackageBuildError("provide a skill name or a contract title")
    name = slugify(candidate) if requested is None or not NAME_RE.fullmatch(candidate) else candidate
    if len(name) > 63 or not NAME_RE.fullmatch(name):
        raise PackageBuildError("skill name must be kebab-case and under 64 characters")
    return name


def _bullet(values: Iterable[str]) -> str:
    return "\n".join(f"- {value}" for value in values)


def _inline(value: str) -> str:
    return value if "`" in value else f"`{value}`"


def _resource_path(value: str) -> str:
    """Get the path portion of a resource declaration without rewriting it."""

    raw = value.strip().strip("`")
    return raw.split(": ", 1)[0].strip()


def _resource_plan(
    resources: list[str],
    resource_root: str | Path | None,
    package_dir: Path,
) -> list[tuple[Path, Path]]:
    """Resolve declared relative resources and leave external prerequisites external."""

    if resources == ["none"]:
        return []
    root = Path(resource_root).resolve() if resource_root is not None else None
    plan: list[tuple[Path, Path]] = []
    for declaration in resources:
        relative_name = _resource_path(declaration)
        if Path(relative_name).is_absolute() or WINDOWS_ABSOLUTE_RE.match(relative_name):
            # Absolute paths are source prerequisites; they are recorded in the
            # generated instructions but are never copied from the host.
            continue
        if root is None:
            raise PackageBuildError(
                f"relative resource {relative_name!r} needs --resource-root before package build"
            )
        source = (root / Path(relative_name)).resolve()
        if root not in source.parents or not source.is_file():
            raise PackageBuildError(f"declared resource is missing or outside resource root: {relative_name}")
        target = (package_dir / Path(relative_name)).resolve()
        if package_dir.resolve() not in target.parents:
            raise PackageBuildError(f"declared resource escapes package destination: {relative_name}")
        plan.append((source, target))
    return plan


def _managed_names(package_dir: Path, *, require_files: bool = False) -> list[str]:
    manifest = package_dir / MANAGED_MANIFEST
    if not manifest.is_file():
        return []
    try:
        data = json.loads(manifest.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise PackageBuildError(f"managed-resource manifest is unreadable: {manifest}") from exc
    values = data.get("managed_resources") if isinstance(data, dict) else None
    if not isinstance(data, dict) or data.get("format") != 1:
        raise PackageBuildError(f"managed-resource manifest has an unsupported format: {manifest}")
    if not isinstance(values, list) or any(not isinstance(value, str) for value in values):
        raise PackageBuildError(f"managed-resource manifest is invalid: {manifest}")
    root = package_dir.resolve()
    normalized: list[str] = []
    for value in values:
        if not value or Path(value).is_absolute() or WINDOWS_ABSOLUTE_RE.match(value):
            raise PackageBuildError(f"managed-resource manifest contains an unsafe path: {value!r}")
        target = (root / Path(value)).resolve()
        if root not in target.parents:
            raise PackageBuildError(f"managed-resource manifest escapes package: {value!r}")
        if require_files and not target.is_file():
            raise PackageBuildError(f"managed resource is missing: {value}")
        normalized.append(target.relative_to(root).as_posix())
    return sorted(set(normalized))


def _write_managed_manifest(package_dir: Path, names: list[str]) -> None:
    payload = {
        "format": 1,
        "managed_resources": sorted(set(names)),
    }
    _write_atomic(
        package_dir / MANAGED_MANIFEST,
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
    )


def _remove_superseded_resources(package_dir: Path, previous: list[str], current: list[str]) -> None:
    current_set = set(current)
    for relative_name in previous:
        if relative_name in current_set:
            continue
        target = (package_dir / relative_name).resolve()
        if package_dir.resolve() not in target.parents or not target.is_file():
            continue
        target.unlink()
        parent = target.parent
        while parent != package_dir.resolve() and parent.is_dir() and not any(parent.iterdir()):
            parent.rmdir()
            parent = parent.parent


def _assert_no_symlinks(root: Path, *, label: str) -> None:
    """Keep package build and install boundaries inside the named tree."""

    if root.is_symlink():
        raise PackageBuildError(f"{label} must not be a symbolic link: {root}")
    try:
        paths = root.rglob("*")
    except OSError as exc:
        raise PackageBuildError(f"cannot inspect {label}: {root}") from exc
    for path in paths:
        if path.is_symlink():
            raise PackageBuildError(f"{label} contains a symbolic link: {path}")


def _description(contract: dict[str, Any]) -> str:
    trigger_text = " ".join(contract["triggers"])
    return f"{contract['purpose'].strip()} {trigger_text.strip()}".replace("  ", " ")


def _revision(contract: dict[str, Any]) -> str:
    canonical = json.dumps(contract, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def render_skill(contract: dict[str, Any], name: str) -> str:
    """Render a deterministic, direct-instruction SKILL.md from a contract."""

    revision = _revision(contract)
    invocation = contract["invocation_type"]
    invocation_rule = (
        "Run only after the user explicitly selects this Skill. If the work needs another user-invoked Skill, recommend it with the required input and stop; do not invoke it silently."
        if invocation == "user-invoked"
        else "Use this Skill when a listed trigger is present. Do not silently invoke another user-invoked Skill; recommend it and wait for the user's choice."
    )
    resources = contract["resources"]
    resource_section = (
        "- No additional resources are required by the source method."
        if resources == ["none"]
        else _bullet(_inline(item) for item in resources)
    )
    evidence = contract.get("source_evidence", {})
    evidence_lines: list[str] = []
    for label in ("commands", "paths", "decisions", "corrections", "failure_modes"):
        values = evidence.get(label, []) if isinstance(evidence, dict) else []
        if isinstance(values, list) and values:
            evidence_lines.append(f"### {label.replace('_', ' ').title()}\n{_bullet(_inline(str(item)) for item in values)}")
    evidence_section = "\n\n".join(evidence_lines) if evidence_lines else "- No additional evidence was supplied beyond the contract fields."

    workflow_lines: list[str] = []
    for index, step in enumerate(contract["ordered_method"], 1):
        workflow_lines.append(f"{index}. {step}\n   - Completion criterion: record the result of this step before continuing.")

    return f"""---
name: {name}
description: {json.dumps(_description(contract), ensure_ascii=False)}
---

<!-- Generated by learn-anything package build. Contract revision: {revision} -->

# {contract.get('title', name)}

## Purpose

{contract['purpose']}

## Invocation and Boundaries

- Invocation type: **{invocation}**.
- {invocation_rule}
- Stop with a precise blocker or failure report when a listed failure mode applies; do not manufacture missing evidence.

## Triggers

{_bullet(contract['triggers'])}

## Inputs

{_bullet(contract['inputs'])}

## Workflow

{chr(10).join(workflow_lines)}

## Decisions

{_bullet(contract['decisions'])}

## Constraints

{_bullet(contract['constraints'])}

## Failure Modes

{_bullet(contract['failure_modes'])}

## Outputs

{_bullet(contract['outputs'])}

## Required Resources

{resource_section}

## Preserved Source Evidence

{evidence_section}

## Quality Checks

{_bullet(contract['verification'])}

## Completion Criteria

- Every Workflow step has a recorded result.
- The declared Outputs exist and are traceable to the source method.
- Every Quality Check passes, or the matching failure/blocker is reported without claiming success.
"""


def _read_frontmatter_name(skill_file: Path) -> str:
    text = skill_file.read_text(encoding="utf-8")
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        raise PackageBuildError(f"{skill_file} has no valid name frontmatter")
    try:
        closing = lines.index("---", 1)
    except ValueError as exc:
        raise PackageBuildError(f"{skill_file} has no valid name frontmatter") from exc
    fields: dict[str, str] = {}
    for line in lines[1:closing]:
        match = re.fullmatch(r"\s*([A-Za-z_][A-Za-z0-9_-]*):\s*(\S.*)\s*", line)
        if not match or match.group(1) in fields:
            raise PackageBuildError(f"{skill_file} has invalid frontmatter")
        fields[match.group(1)] = match.group(2).strip()
    if set(fields) != {"name", "description"}:
        raise PackageBuildError(f"{skill_file} frontmatter must contain only name and description")
    return fields["name"]


def _marker(skill_file: Path) -> str | None:
    try:
        text = skill_file.read_text(encoding="utf-8")
    except (OSError, IndexError, UnicodeDecodeError):
        return None
    for line in text.splitlines():
        match = MARKER_RE.fullmatch(line.strip())
        if match:
            return match.group(1)
    return None


def _write_atomic(path: Path, content: str | bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(content, bytes):
        handle = tempfile.NamedTemporaryFile("wb", dir=path.parent, delete=False)
    else:
        handle = tempfile.NamedTemporaryFile("w", encoding="utf-8", newline="\n", dir=path.parent, delete=False)
    with handle:
        handle.write(content)
        temporary = Path(handle.name)
    temporary.replace(path)


def build_package(
    payload: dict[str, Any],
    output_root: str | Path,
    *,
    name: str | None = None,
    allow_update: bool = False,
    resource_root: str | Path | None = None,
) -> dict[str, Any]:
    """Create or update one package, preserving unrelated existing resources."""

    contract = validate_contract(payload)
    package_name = _name_for_contract(contract, name)
    package_dir = Path(output_root).resolve() / package_name
    skill_file = package_dir / "SKILL.md"
    rendered = render_skill(contract, package_name)
    resource_plan = _resource_plan(contract["resources"], resource_root, package_dir)
    managed_names = sorted(target.relative_to(package_dir).as_posix() for _, target in resource_plan)

    if package_dir.is_symlink():
        raise PackageBuildError(f"package destination is a symbolic link: {package_dir}")
    if package_dir.exists() and not package_dir.is_dir():
        raise PackageBuildError(f"package destination is not a directory: {package_dir}")
    if package_dir.exists():
        _assert_no_symlinks(package_dir, label="package destination")
    if not package_dir.exists():
        package_dir.mkdir(parents=True)
        _write_atomic(skill_file, rendered)
        for source, target in resource_plan:
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, target)
        _write_managed_manifest(package_dir, managed_names)
        return {"outcome": "created", "name": package_name, "package": str(package_dir), "revision": _revision(contract)}

    existing_marker = _marker(skill_file) if skill_file.exists() else None
    previous_managed_names = _managed_names(package_dir) if existing_marker is not None else []
    resources_match = all(target.is_file() and target.read_bytes() == source.read_bytes() for source, target in resource_plan)
    manifest_match = previous_managed_names == managed_names
    if skill_file.exists() and skill_file.read_text(encoding="utf-8") == rendered and resources_match and manifest_match:
        return {"outcome": "no-op", "name": package_name, "package": str(package_dir), "revision": _revision(contract)}
    if existing_marker is None and not allow_update:
        return {
            "outcome": "duplicate",
            "name": package_name,
            "package": str(package_dir),
            "reason": "an unowned package already exists; pass allow_update only with explicit authority",
        }
    if not allow_update and existing_marker is not None:
        raise PackageBuildError("existing generated package differs; pass allow_update to update it")

    _remove_superseded_resources(package_dir, previous_managed_names, managed_names)
    _write_atomic(skill_file, rendered)
    for source, target in resource_plan:
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, target)
    _write_managed_manifest(package_dir, managed_names)
    return {"outcome": "updated", "name": package_name, "package": str(package_dir), "revision": _revision(contract)}


def _same_tree(left: Path, right: Path) -> bool:
    """Return whether every source file matches, ignoring destination extras."""

    left_dirs = sorted(
        path.relative_to(left).as_posix()
        for path in left.rglob("*")
        if path.is_dir() and not path.is_symlink()
    )
    left_files = sorted(path.relative_to(left).as_posix() for path in left.rglob("*") if path.is_file())
    return all((right / relative).is_dir() for relative in left_dirs) and all(
        (right / relative).is_file() and (left / relative).read_bytes() == (right / relative).read_bytes()
        for relative in left_files
    )


def install_package(
    package_dir: str | Path,
    install_root: str | Path,
    *,
    allow_update: bool = False,
) -> dict[str, Any]:
    """Install a package into a clean host directory idempotently."""

    source_input = Path(package_dir)
    if source_input.is_symlink():
        raise PackageBuildError("install source must not be a symbolic link")
    source = source_input.resolve()
    if not source.is_dir() or not (source / "SKILL.md").is_file():
        raise PackageBuildError("install source must contain a SKILL.md")
    _assert_no_symlinks(source, label="install source")
    if _marker(source / "SKILL.md") is None:
        raise PackageBuildError("install source is not a generated learn-anything package")
    if not (source / MANAGED_MANIFEST).is_file():
        raise PackageBuildError("install source is missing its managed-resource manifest")
    _managed_names(source, require_files=True)
    name = _read_frontmatter_name(source / "SKILL.md")
    if not NAME_RE.fullmatch(name):
        raise PackageBuildError("installed package name must be kebab-case")
    if source.name != name:
        raise PackageBuildError("install source directory must match its frontmatter name")
    destination = Path(install_root).resolve() / name
    if destination.is_symlink():
        raise PackageBuildError(f"install destination is a symbolic link: {destination}")
    if destination.exists() and not destination.is_dir():
        raise PackageBuildError(f"install destination is not a directory: {destination}")
    if destination.exists():
        _assert_no_symlinks(destination, label="install destination")
    if not destination.exists():
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copytree(source, destination)
        return {"outcome": "installed", "name": name, "package": str(destination)}
    current_managed_names = _managed_names(source)
    previous_managed_names = _managed_names(destination)
    stale_managed = set(previous_managed_names) - set(current_managed_names)
    if _same_tree(source, destination) and not stale_managed:
        return {"outcome": "no-op", "name": name, "package": str(destination)}
    if not allow_update:
        return {"outcome": "duplicate", "name": name, "package": str(destination), "reason": "different package already installed"}
    _remove_superseded_resources(destination, previous_managed_names, current_managed_names)
    for source_path in source.rglob("*"):
        relative = source_path.relative_to(source)
        target = destination / relative
        if source_path.is_dir():
            target.mkdir(parents=True, exist_ok=True)
        else:
            _write_atomic(target, source_path.read_text(encoding="utf-8") if source_path.suffix.lower() in {".md", ".json", ".yaml", ".yml", ".txt"} else source_path.read_bytes())
    return {"outcome": "updated", "name": name, "package": str(destination)}


def _load_json(path: str | None) -> dict[str, Any]:
    raw = Path(path).read_text(encoding="utf-8") if path else sys.stdin.read()
    payload = json.loads(raw)
    if not isinstance(payload, dict):
        raise PackageBuildError("contract input must be a JSON object")
    return payload


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--contract-file", help="JSON envelope emitted by skill_candidate_builder")
    parser.add_argument("--output-root", required=True, help="Parent directory for the generated package")
    parser.add_argument("--name", help="Optional kebab-case package name; otherwise derive it from title")
    parser.add_argument("--resource-root", help="Root from which declared relative resources may be copied")
    parser.add_argument("--update", action="store_true", help="Allow updating an existing package")
    args = parser.parse_args(argv)
    try:
        result = build_package(
            _load_json(args.contract_file),
            args.output_root,
            name=args.name,
            allow_update=args.update,
            resource_root=args.resource_root,
        )
    except (OSError, PackageBuildError, json.JSONDecodeError) as exc:
        print(json.dumps({"outcome": "blocked", "reason": str(exc)}, ensure_ascii=False, indent=2))
        return 2
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
